version: '3'

services:
    web:
        build: ./web            
        ports: 
            - "3000:3000"
        stdin_open: true
    graphql:
        build: ./graphql
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_HOST
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_DB
    mongo:
        image: mongo
